name: github pages


on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2


      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'


      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install WeasyPrint
        run: |
          sudo apt-get -y update
          sudo apt-get install build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
          sudo apt-get install -y weasyprint
          weasyprint --version

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          GATSBY_REPOSITORY_OWNER: nauchikus
          GATSBY_REPOSITORY_NAME: typescript-definitive-guide
          GATSBY_REPOSITORY_BRANCH: master
        working-directory: ./
        run: |
          cd ./www
          npm ci
          npm run build && npm run export
          cd ../pdf
          npm ci
          npm run build
          cd ../
          mkdir public
          mkdir public/pdf
          cp -r ./www/out/* ./public
          mv ./pdf/public/tdg.pdf ./public/pdf
          cp ./www/public/CNAME ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
